name: Java CI

on:
  push:
    branches:
      - master
      - $protected-branches
  pull_request:
    branches:
      - master
  schedule:
  - cron: "23 21 * * 2"
  workflow_dispatch:

jobs:
  call-workflow:
    strategy:
      matrix:
        josm-revision: ["", "r17896"]
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v2
    with:
      josm-revision: ${{ matrix.josm-revision }}
      perform-revision-tagging: ${{ github.repository == 'tsmock/CADTools' && github.ref_type == 'branch' && github.ref_name == 'master' && github.event_name != 'schedule' && github.event_name != 'pull_request' && matrix.josm-revision == 'r17896' }}
